config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  get 'contact/index'
  resources :galleries
  resources :products
  resources :meetings
  resources :news_posts
  resources :comments
  get 'about_us/Index'
  resources :events
  resources :members

  resources :events do
    member do
      get :delete
    end
  end
  resources :news_posts do
    member do
      get :delete
    end
  end
  resources :galleries do
    member do
      get :delete
    end
  end
  resources :comments do
    member do
      get :delete
    end
  end
  resources :meetings do
    member do
      get :delete
    end
  end
  resources :products do
    member do
      get :delete
    end
  end
  resources :members do
    member do
      get :delete
    end
  end

  get 'landing/Index'
  root 'landing#Index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/meeting.rb
# frozen_string_literal: true

class Meeting < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :meeting_date, presence: true
  validates :location, presence: true
  has_one_attached :photo

  # Only allowed files for the image are PNG, JPG, JPEG
  validates :photo, attached: false, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/controllers/meetings_controller.rb
# frozen_string_literal: true

class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: %i[show edit update destroy]

  # GET /meetings or /meetings.json
  def index
    @meetings = Meeting.all
  end

  # GET /meetings/1 or /meetings/1.json
  def show; end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit; end

  # POST /meetings or /meetings.json
  def create
    @meeting = Meeting.new(meeting_params)

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1 or /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @meeting = Meeting.find(params[:id])
  end

  # DELETE /meetings/1 or /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_meeting
    @meeting = Meeting.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def meeting_params
    params.require(:meeting).permit(:title, :description, :meeting_date, :location, :photo)
  end
end

app/helpers/meetings_helper.rb
# frozen_string_literal: true

module MeetingsHelper
end

app/views/meetings/_form.html.erb
<head>
  <style>
    h1 {
      text-align: center;
    }

    .container {
      max-width: 31em;
      margin: 0 auto;
      padding: 20px;
    }

    .bigger-container {
      max-width: 35em;
      margin: 0 auto;
      background-color: #f2f2f2;
    }

    input {
      padding: 12px 20px;
      width: 400px;
      margin: 8px 0;
      box-sizing: border-box;
    }

    input[type=text]:focus {
      background-color: lightgrey;
      word-wrap: break-word;
        word-break: break-all;
    }

    textarea {
      width: 400px;
      height: 100px;
    }


  </style>
</head>

<% # Check if the current user is the ADMIN %>
<% if current_user.uid == "110391296899575374577" %>

  <div class="bigger-container">
    <div class="container">

    <% # Displaying any errors found when submitting the form %>
    <%= form_with(model: meeting) do |form| %>
      <% if meeting.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

          <ul>
            <% meeting.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% # Displaying field to input title %>
      <div class="field">
        <%= form.label :title %>
        <br>
        <%= form.text_field :title, placeholder: "Enter title.." %>
      </div>

      <% # Displaying field to input description %>
      <div class="field">
        <%= form.label :description %>
        <br>
        <%= form.text_area :description, placeholder: "Enter description.." %>
      </div>

      <% # Displaying field to input date and time %>
      <div class="field", style="max-width: 13rem">
        <%= form.label :meeting_date, "Date and time" %>
        <br>
        <%= form.datetime_field :meeting_date %>
      </div>

      <% # Displaying field to input location %>
      <div class="field">
        <%= form.label :location %>
        <br>
        <%= form.text_field :location, placeholder: "Enter location.." %>
      </div>

      <% # Displaying field to upload a photo %>
      <div class="field">
        <%= form.file_field :photo %>
      </div>

      <% # Displaying submit button %>
      <div class="actions">
        <%= form.submit %>
      </div>

    <% end %>
    </div>
  </div>
<% else %>
<% # Redirecting the user if they are not an ADMIN %>
  <center>
  <h1>You're not an admin!</h1>
  <%= link_to 'Back', meetings_path %>
  </center>
<% end %>

app/views/meetings/delete.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      text-align: center;
    }

    .css_img {
      width: 100%;
    }

    .container {
      max-width: 65em;
      margin: 0 auto;
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }

    .del-meeting {
      text-align: center;
    }

  </style>
</head>

<% # Check if the current user is the ADMIN %>
<% if current_user.uid == "110391296899575374577" %>
  <p id="notice"><%= notice %></p>

  <% # Displaying title of meeting post to be deleted %>
  <h1> Deleting <%= @meeting.title %> </h1>

  <div class="del-meeting">
    <%= form_for(@meeting, :method => 'delete') do |f| %>

      <p>Are you sure you want to permanently delete this meeting?</p>
      <p><%= @meeting.title %></p>

      <% # Displaying buttons to confirm and cancel deletion %>
      <div class="form-buttons">
        <%= f.submit("Delete meeting") %>
        <%= link_to '<button type="button"> Back </button>'.html_safe, meetings_path %>
      </div>

    <% end %>
    <br>
    <br>
  </div>

<% # Displaying the meeting post to be deleted %>
  <div class="container">
          <div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-4">
              <% if @meeting.photo.attached? %>
                <%= image_tag(@meeting.photo, width: 200) %>
              <% else %>
                <%= image_tag("https://nick-network.s3.us-east-2.amazonaws.com/Default.jpg", class: "css_img") %>
              <% end %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <p class="card-text"> <%= @meeting.description %> </p>
                </div>

                <table class="table table-sm">
                  <colgroup>
                    <col span="1" style="width: 28%;">
                    <col span="1" style="width: 72%;">
                  </colgroup>

                  <tbody>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Time </th>
                      <td> <%= @meeting.meeting_date.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                    </tr>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Location </th>
                      <td> <%= @meeting.location %> </td>
                    </tr>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Created on </th>
                      <td> <%= @meeting.created_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                    </tr>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Last updated on </th>
                      <td> <%= @meeting.updated_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
  </div>
  <% else %>
  <% # If the user is not an ADMIN, redirect them back %>
    <center>
    <h1>You're not an admin!</h1>
    <%= link_to 'Back', meetings_path %>
    </center>
  <% end %>

app/views/meetings/edit.html.erb
<% # Check if the current user is the ADMIN %>
<% if current_user.uid == "110391296899575374577" %>
  <h1>Editing Meeting</h1>

  <% # Rendeting Editing form %>
  <%= render 'form', meeting: @meeting %>

  <% # Rendering buttons to cancel changes %>
  <div class="container", style="margin-left: 12em;">
    <%= link_to '<button type="button"> Back </button>'.html_safe, @meeting %>
  </div>
<% else %>
<% # If the user is not an ADMIN, redirect them back %>
  <center>
  <h1>You're not an admin!</h1>
  <%= link_to 'Back', meetings_path %>
  </center>
<% end %>

app/views/meetings/index.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      border-radius: 2em;
      text-align: center;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .card:hover{
      box-shadow: 0 5px 10px rgba(0,0,0,.5);
    }

    .list-group-flush .list-group-item {
      font-size: 15px;
    }

    .css_img {
      border-radius: 2em 0em 0em 2em;
      width: 110%;
    }

    .container {
      max-width: 65em;
      margin: 0 auto;
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }


 </style>
</head>

<p id="notice"><%= notice %></p>

<h1>Meetings</h1>

<% # If the user is an ADMIN, they can create a new meeting %>
<div class="button-container">
  <% if current_user.uid == "110391296899575374577" %>
    <%= link_to '<button type="button">Add New meeting</button>'.html_safe, new_meeting_path %>
  <% end %>
</div>


<br>
<div class="container">

  <% # Loop that displays all meeting posts in separate cards %>
  <% @meetings.each do |meeting| %>
        <div class="card mb-3" style="border: 3px solid black;">
          <div class="row g-0">

            <% # Displaying image inside the card, if no image is attached %>
            <% # then it displays a default image %>
            <div class="col-md-3">
            <% if meeting.photo.attached? %>
              <%= image_tag(meeting.photo, width: 200) %>
            <% else %>
              <%= image_tag("https://nick-network.s3.us-east-2.amazonaws.com/Default.jpg", class: "css_img") %>
            <% end %>
            </div>

            <% # Displaying only 189 characters from the description, as %>
            <% # more characters can interfeer with the image outline %>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title", style="font-size: 19px;"> <%= meeting.title %> </h5>
                <p class="card-text"> <%= meeting.description[0..189] %> </p>
              </div>

              <% # Adjusting sizing to display what each fied is %>
              <table class="table table-sm">
                <colgroup>
                  <col span="1" style="width: 15%;">
                  <col span="1" style="width: 70%;">
                </colgroup>

                <tbody>

                  <% # Displaying time in MM/DD/YYYY format %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Time </th>
                    <td> <%= meeting.meeting_date.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                  </tr>

                  <% # Displaying location %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Location </th>
                    <td> <%= meeting.location %> </td>
                  </tr>
                </tbody>
              </table>

              <% # ADMIN can edit and delete meeting posts, regular member %>
              <% # can only view %>
              <div class="card-body">
                <%= link_to 'View', meeting, :class => "btn btn-primary" %>
                <% if current_user.uid == "110391296899575374577" %>
                  <%= link_to 'Edit', edit_meeting_path(meeting), :class => "btn btn-primary"%>
                  <%= link_to 'Destroy', delete_meeting_path(meeting), :class => "btn btn-primary"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <br>
  <% end %>
</div>

app/views/meetings/new.html.erb
<% # Only ADMIN is allowed on this page %>
<% if current_user.uid == "110391296899575374577" %>
  <h1>New Meeting</h1>

  <% # Rendering meeting form %>
  <%= render 'form', meeting: @meeting %>

  <% # Button to cancel creation of new meeting %>
  <center>
    <%= link_to '<button type="button"> Back </button>'.html_safe, meetings_path %>
  </center>
<% else %>
<% # Redirectering user if they aren't an ADMIN %>
  <center>
  <h1>You're not an admin!</h1>
  <%= link_to 'Back', meetings_path %>
  </center>
<% end %>

app/views/meetings/show.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      text-align: center;
    }

    .css_img {
      width: 100%;
    }

    .container {
      max-width: 65em;
      margin: 0 auto;
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }


 </style>
</head>

<p id="notice"><%= notice %></p>

<% # Displaying title of meeting %>
<h1> <%= @meeting.title %> </h1>
<div class="container">
        <div class="card mb-3">
          <div class="row g-0">

            <% # Displaying image iside the card, if no image is attached %>
            <% # then it displays a default image %>
            <div class="col-md-4">
              <% if @meeting.photo.attached? %>
                <%= image_tag(@meeting.photo, width: 200) %>
              <% else %>
                <%= image_tag("https://nick-network.s3.us-east-2.amazonaws.com/Default.jpg", class: "css_img") %>
              <% end %>
            </div>

            <div class="col-md-8">

              <% # Displaying Description %>
              <div class="card-body">
                <p class="card-text"> <%= @meeting.description %> </p>
              </div>

              <% # Adjusting sizing to display what each fied is %>
              <table class="table table-sm">
                <colgroup>
                  <col span="1" style="width: 28%;">
                  <col span="1" style="width: 72%;">
                </colgroup>

                <tbody>

                  <% # Displaying time in MM/DD/YYYY format %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Time </th>
                    <td> <%= @meeting.meeting_date.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                  </tr>

                  <% # Displaying location %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Location </th>
                    <td> <%= @meeting.location %> </td>
                  </tr>

                  <% # Displaying when the post was created %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Created on </th>
                    <td> <%= @meeting.created_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                  </tr>

                  <% # Displaying when the post was last updated/edited %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Last updated on </th>
                    <td> <%= @meeting.updated_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <% # ADMIN can edit and delete events, regular member can %>
        <% # only view %>
        <div class="container", style="margin-left: 30em;">
          <% if current_user.uid == "110391296899575374577" %>
            <%= link_to '<button type="button"> Edit </button>'.html_safe, edit_meeting_path(@meeting) %>
          <% end %>
          <%= link_to '<button type="button"> Back </button>'.html_safe, meetings_path %>
        </div>
</div>