config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: :new_user_session
    get 'users/sign_out', to: 'users/sessions#destroy', as: :destroy_user_session
  end
  get 'contact/index'
  resources :galleries
  resources :products
  resources :meetings
  resources :news_posts
  resources :comments
  get 'about_us/Index'
  resources :events
  resources :members

  resources :events do
    member do
      get :delete
    end
  end
  resources :news_posts do
    member do
      get :delete
    end
  end
  resources :galleries do
    member do
      get :delete
    end
  end
  resources :comments do
    member do
      get :delete
    end
  end
  resources :meetings do
    member do
      get :delete
    end
  end
  resources :products do
    member do
      get :delete
    end
  end
  resources :members do
    member do
      get :delete
    end
  end

  get 'landing/Index'
  root 'landing#Index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
  has_one_attached :photo

  # Only allowed files for the image are PNG, JPG, JPEG
  validates :photo, attached: false, content_type: ['image/png', 'image/jpg', 'image/jpeg']
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_product, only: %i[show edit update destroy]

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show; end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit; end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @product = Product.find(params[:id])
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def product_params
    params.require(:product).permit(:name, :description, :price, :photo)
  end
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/products/_form.html.erb
<head>
  <style>
    h1 {
      text-align: center;
    }

    .container {
      max-width: 31em;
      margin: 0 auto;
      padding: 20px;
    }

    .bigger-container {
      max-width: 35em;
      margin: 0 auto;
      background-color: #f2f2f2;
    }

    input {
      padding: 12px 20px;
      width: 400px;
      margin: 8px 0;
      box-sizing: border-box;
    }

    input[type=text]:focus {
      background-color: lightgrey;
      word-wrap: break-word;
        word-break: break-all;
    }

    textarea {
      width: 400px;
      height: 100px;
    }


  </style>
</head>

<% # Check if the current user is the ADMIN %>
<% if current_user.uid == "110391296899575374577" %>

  <div class="bigger-container">
    <div class="container">

    <% # Displaying any errors found when submitting the form %>
    <%= form_with(model: product) do |form| %>
      <% if product.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

          <ul>
            <% product.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <% # Displaying field to input product name %>
      <div class="field">
        <%= form.label :name %>
        <br>
        <%= form.text_field :name, placeholder: "Enter Product Name" %>
      </div>

      <% # Displaying field to input product description %>
      <div class="field">
        <%= form.label :description %>
        <br>
        <%= form.text_area :description, placeholder: "Enter Product Description.." %>
      </div>

      <% # Displaying field to input price %>
      <div class="field", style="max-width: 13rem">
        <%= form.label :price, "Enter Product Cost" %>
        <br>
        <%= form.text_field :price %>
      </div>

      <% # Displaying field to upload a photo %>
      <div class="field">
        <%= form.file_field :photo %>
      </div>

      <% # Displaying submit button %>
      <div class="actions">
        <%= form.submit %>
      </div>

    <% end %>
  </div>
  <% else %>
  <% # Redirecting the user if they are not an ADMIN %>
    <center>
    <h1>You're not an admin!</h1>
    <%= link_to 'Back', products_path %>
    </center>
  <% end %>

app/views/products/delete.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      text-align: center;
    }

    .css_img {
      width: 100%;
    }

    .container {
      max-width: 65em;
      margin: 0 auto;
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }

    .del-product {
      text-align: center;
    }

  </style>
</head>


<% # Check if the current user is the ADMIN %>
<% if current_user.uid == "110391296899575374577" %>
  <p id="notice"><%= notice %></p>

  <% # Displaying title of product to be deleted %>
  <h1> Deleting <%= @product.name %> </h1>

  <div class="del-product">
    <%= form_for(@product, :method => 'delete') do |f| %>

      <p>Are you sure you want to permanently delete this product?</p>
      <p><%= @product.name %></p>

      <% # Displaying buttons to confirm and cancel deletion %>
      <div class="form-buttons">
        <%= f.submit("Delete product") %>
        <%= link_to '<button type="button"> Back </button>'.html_safe, products_path %>
      </div>

    <% end %>
    <br>
    <br>
  </div>

<% # Displaying the product to be deleted %>
  <div class="container">
          <div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-4">
              <% if @product.photo.attached? %>
                <%= image_tag(@product.photo, width: 200) %>
              <% else %>
                <%= image_tag("https://nick-network.s3.us-east-2.amazonaws.com/Default.jpg", class: "css_img") %>
              <% end %>
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <p class="card-text"> <%= @product.description %> </p>
                </div>

                <table class="table table-sm">
                  <colgroup>
                    <col span="1" style="width: 28%;">
                    <col span="1" style="width: 72%;">
                  </colgroup>

                  <tbody>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Name </th>
                      <td> <%= @product.name %> </td>
                    </tr>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Price </th>
                      <td> <%= "%.2f" % @product.price %> </td>
                    </tr>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Created on </th>
                      <td> <%= @product.created_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                    </tr>
                    <tr>
                      <th scope="row", style="font-weight: normal; color: gray;"> Last updated on </th>
                      <td> <%= @product.updated_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
  </div>
  <% else %>
  <% # If the user is not an ADMIN, redirect them back %>
    <center>
    <h1>You're not an admin!</h1>
    <%= link_to 'Back', products_path %>
    </center>
  <% end %>

app/views/products/edit.html.erb
<% # Check if the current user is the ADMIN %>
<% if current_user.uid == "110391296899575374577" %>
  <h1>Editing product</h1>

  <% # Rendeting Editing form %>
  <%= render 'form', product: @product %>

  <% # Rendering buttons to cancel changes %>
  <div class="container", style="margin-left: 12em;">
    <%= link_to '<button type="button"> Back </button>'.html_safe, @product %>
  </div>
  <% else %>
  <% # If the user is not an ADMIN, redirect them back %>
    <center>
    <h1>You're not an admin!</h1>
    <%= link_to 'Back', products_path %>
    </center>
  <% end %>

app/views/products/index.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      border-radius: 2em;
      text-align: center;
      box-shadow: 0 5px 10px rgba(0,0,0,.2);
    }

    .card:hover{
      box-shadow: 0 5px 10px rgba(0,0,0,.5);
    }

    .list-group-flush .list-group-item {
      font-size: 15px;
    }

    .css_img {
      border-radius: 2em 0em 0em 2em;
      width: 110%;
    }

    .container {
      max-width: 65em;
      margin: 0 auto;
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }

    .contact {
      text-align:center;
      font-size:24px;
    }

 </style>
</head>

<p id="notice"><%= notice %></p>

<h1>Products</h1>

<% # If the user is an ADMIN, they can create a new product post %>
<div><center>

  <h5>
    <% results = ActiveRecord::Base.connection.exec_query("select id from members where email='theaggienickwork@gmail.com'") %>
    Please Contact the administrator for purchase inquiries.<br><br>
    <%= link_to '<button type="button"> Contact </button>'.html_safe, member_url(results.rows[0][0]) %><br>
  </h5>

  <div class="button-container">
  <% if current_user.uid == "110391296899575374577" %>
    <%= link_to '<button type="button">Add New product</button>'.html_safe, new_product_path %>
  <% end %>
  </div>

</div></center>

<br>



<div class="container">

  <% # Loop that displays all procuts in separate cards %>
  <% @products.each do |product| %>
        <div class="card mb-3" style="border: 3px solid black;">
          <div class="row g-0">

            <% # Displaying image inside the card, if no image is attached %>
            <% # then it displays a default image %>
            <div class="col-md-3">
            <% if product.photo.attached? %>
              <%= image_tag(product.photo, width: 200) %>
            <% else %>
              <%= image_tag("https://nick-network.s3.us-east-2.amazonaws.com/Default.jpg", class: "css_img") %>
            <% end %>
            </div>

            <% # Displaying only 189 characters from the description, as %>
            <% # more characters can interfeer with the image outline %>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-name", style="font-size: 19px;"> <%= product.name %> </h5>
                <p class="card-text"> <%= product.description[0..189] %> </p>
              </div>

              <% # Adjusting sizing to display what each fied is %>
              <table class="table table-sm">
                <colgroup>
                  <col span="1" style="width: 15%;">
                  <col span="1" style="width: 70%;">
                </colgroup>

                <tbody>

                  <% # Displaying price %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Price </th>
                    <td> <%= "%.2f" % product.price %> </td>
                  </tr>
                </tbody>
              </table>

              <% # ADMIN can edit and delete events, regular member can %>
              <% # only view %>
              <div class="card-body">
                <%= link_to 'View', product, :class => "btn btn-primary" %>
                <% if current_user.uid == "110391296899575374577" %>
                  <%= link_to 'Edit', edit_product_path(product), :class => "btn btn-primary"%>
                  <%= link_to 'Destroy', delete_product_path(product), :class => "btn btn-primary"%>
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <br>
  <% end %>
</div>

app/views/products/new.html.erb
<% # Only ADMIN is allowed on this page %>
<% if current_user.uid == "110391296899575374577" %>
  <h1>New Product</h1>

  <% # Rendering event form %>
  <%= render 'form', product: @product %>

  <% # Button to cancel creation of new event %>
  <div class="container", style="margin-left: 10em;">
    <%= link_to '<button type="button"> Back </button>'.html_safe, products_path %>
  </div>
<% else %>
  <% # Redirectering user if they aren't an ADMIN %>
  <center>
  <h1>You're not an admin!</h1>
  <%= link_to 'Back', products_path %>
  </center>
<% end %>

app/views/products/show.html.erb
<head>
  <style>

    h1 {
      text-align: center;
    }

    .card {
      text-align: center;
    }

    .css_img {
      width: 100%;
    }

    .container {
      max-width: 65em;
      margin: 0 auto;
    }

    .button-container {
      margin-left: auto;
      margin-right: auto;
      justify-content: center;
      width: 8em;
    }


 </style>
</head>

<p id="notice"><%= notice %></p>

<% # Displaying title of event %>
<h1> <%= @product.name %> </h1>
<div class="container">
        <div class="card mb-3">
          <div class="row g-0">

            <% # Displaying image iside the card, if no image is attached %>
            <% # then it displays a default image %>
            <div class="col-md-4">
            <% if @product.photo.attached? %>
              <%= image_tag(@product.photo, width: 200) %>
            <% else %>
              <%= image_tag("https://nick-network.s3.us-east-2.amazonaws.com/Default.jpg", class: "css_img") %>
            <% end %>
            </div>

            <div class="col-md-8">

              <% # Displaying Description %>
              <div class="card-body">
                <p class="card-text"> <%= @product.description %> </p>
              </div>

              <% # Adjusting sizing to display what each fied is %>
              <table class="table table-sm">
                <colgroup>
                  <col span="1" style="width: 28%;">
                  <col span="1" style="width: 72%;">
                </colgroup>

                <tbody>

                  <% # Displaying time in MM/DD/YYYY format %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Name </th>
                    <td> <%= @product.name %> </td>
                  </tr>

                  <% # Displaying Price %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Price </th>
                    <td> <%= "%.2f" % @product.price %> </td>
                  </tr>

                  <% # Displaying when the post was created %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Created on </th>
                    <td> <%= @product.created_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                  </tr>

                  <% # Displaying when the post was last updated/edited %>
                  <tr>
                    <th scope="row", style="font-weight: normal; color: gray;"> Last updated on </th>
                    <td> <%= @product.updated_at.strftime("%m/%d/%Y at %I:%M%p") %> </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <% # ADMIN can edit and delete events, regular member can %>
        <% # only view %>
        <div class="container", style="margin-left: 30em;">
          <% if current_user.uid == "110391296899575374577" %>
            <%= link_to '<button type="button"> Edit </button>'.html_safe, edit_product_path(@product) %>
          <% end %>
          <%= link_to '<button type="button"> Back </button>'.html_safe, products_path %>
        </div>
</div>